name: Prism CI

on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/ci.yml
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props
      - xunit.runner.json
      - 'src/**'
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/ci.yml

jobs:
  build-prism-core:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@master
    with:
      name: Build Prism.Core
      solution-path: PrismLibrary_Core.slnf
      code-sign: true
      artifact-name: Core
    secrets:
      codeSignKeyVault: ${{ secrets.CodeSignKeyVault }}
      codeSignClientId: ${{ secrets.CodeSignClientId }}
      codeSignTenantId: ${{ secrets.CodeSignTenantId }}
      codeSignClientSecret: ${{ secrets.CodeSignClientSecret }}
      codeSignCertificate: ${{ secrets.CodeSignCertificate }}

  build-prism-wpf:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@master
    with:
      name: Build Prism.Wpf
      solution-path: PrismLibrary_Wpf.slnf
      code-sign: true
      artifact-name: Wpf
    secrets:
      codeSignKeyVault: ${{ secrets.CodeSignKeyVault }}
      codeSignClientId: ${{ secrets.CodeSignClientId }}
      codeSignTenantId: ${{ secrets.CodeSignTenantId }}
      codeSignClientSecret: ${{ secrets.CodeSignClientSecret }}
      codeSignCertificate: ${{ secrets.CodeSignCertificate }}

  build-prism-forms:
    uses: avantipoint/workflow-templates/.github/workflows/msbuild-build.yml@master
    with:
      name: Build Prism.Forms
      solution-path: PrismLibrary_Forms.slnf
      code-sign: true
      artifact-name: Forms
    secrets:
      codeSignKeyVault: ${{ secrets.CodeSignKeyVault }}
      codeSignClientId: ${{ secrets.CodeSignClientId }}
      codeSignTenantId: ${{ secrets.CodeSignTenantId }}
      codeSignClientSecret: ${{ secrets.CodeSignClientSecret }}
      codeSignCertificate: ${{ secrets.CodeSignCertificate }}

  build-prism-uno:
    uses: avantipoint/workflow-templates/.github/workflows/msbuild-build.yml@master
    with:
      name: Build Prism.Uno
      solution-path: PrismLibrary_Uno.slnf
      dotnet-version: 7.0.102
      windows-sdk-version: 18362
      uno-check: true
      uno-check-parameters: '--skip xcode --skip gtk3 --skip vswin --skip vsmac'
      run-tests: false
      code-sign: true
      artifact-name: Uno
    secrets:
      codeSignKeyVault: ${{ secrets.CodeSignKeyVault }}
      codeSignClientId: ${{ secrets.CodeSignClientId }}
      codeSignTenantId: ${{ secrets.CodeSignTenantId }}
      codeSignClientSecret: ${{ secrets.CodeSignClientSecret }}
      codeSignCertificate: ${{ secrets.CodeSignCertificate }}

  build-prism-maui:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@master
    with:
      name: Build Prism.Maui
      solution-path: PrismLibrary_Maui.slnf
      code-sign: true
      artifact-name: Maui
    secrets:
      codeSignKeyVault: ${{ secrets.CodeSignKeyVault }}
      codeSignClientId: ${{ secrets.CodeSignClientId }}
      codeSignTenantId: ${{ secrets.CodeSignTenantId }}
      codeSignClientSecret: ${{ secrets.CodeSignClientSecret }}
      codeSignCertificate: ${{ secrets.CodeSignCertificate }}

  generate-consolidated-artifacts:
    needs: [build-prism-core, build-prism-wpf, build-prism-forms, build-prism-uno, build-prism-maui]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Core
        uses: actions/download-artifact@v4.1.7
        with:
          name: Core
          path: artifacts\Core

      - name: Download Wpf
        uses: actions/download-artifact@v4.1.7
        with:
          name: Wpf
          path: artifacts\Wpf

      - name: Download Forms
        uses: actions/download-artifact@v4.1.7
        with:
          name: Forms
          path: artifacts\Forms

      - name: Download Uno
        uses: actions/download-artifact@v4.1.7
        with:
          name: Uno
          path: artifacts\Uno

      - name: Download Maui
        uses: actions/download-artifact@v4.1.7
        with:
          name: Maui
          path: artifacts\Maui

      - name: Consolidate Artifacts
        run: build\consolidate-artifacts.ps1
        shell: powershell


      - name: Upload Consolidated NuGets
        uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: .\artifacts\nuget

      - name: Upload Consolidated Binaries
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: .\artifacts\binaries

  deploy-internal:
    uses: avantipoint/workflow-templates/.github/workflows/deploy-nuget.yml@master
    needs: generate-consolidated-artifacts
    if: ${{ github.event_name == 'push' }}
    with:
      name: Deploy Internal
    secrets:
      feedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
      apiKey: ${{ secrets.IN_HOUSE_API_KEY }}

  deploy-sponsors:
    uses: avantipoint/workflow-templates/.github/workflows/deploy-nuget.yml@master
    needs: generate-consolidated-artifacts
    if: ${{ github.event_name == 'push' }}
    with:
      name: Deploy Sponsor Connect
    secrets:
      feedUrl: ${{ secrets.SPONSOR_CONNECT_NUGET_FEED }}
      apiKey: ${{ secrets.SPONSOR_CONNECT_TOKEN }}
